### ISSUE TITLE
Akamai ETP Issue with date/time and gap in log chart due to leap year

### ISSUE THREAD

**Issue by Ginni-Bhatia** [akamai/cli-etp#15] opened 2024-02-29 06:36 UTC
Describe the bug
Noticed gap in log chart for Akamai ETP logs, also noticed that the date/time is in March 2024 instead of 29th Feb 2024.

To Reproduce
Check the logs generated by Akamai ET after 28th Feb midnight or
check the time sync for Akamai ETP

Expected behavior
For today i.e. Feb 29th 2024, Logs should be dated 29th Feb 2024 however they are dated 1st March 2024

Screenshots

![image](https://github.com/akamai/cli-etp/assets/101125352/97b7e2c1-2c71-4ea9-8f72-2634b1cc3b89)

Additional context
Checked logs in Sentinel and found that after 28th Feb Midnight the next date was 1st March, meaning there is no log loss however leap year date is not reflected in Akamai ETP logs

![image](https://github.com/akamai/cli-etp/assets/101125352/6aa732c9-87e2-4ec7-8aae-0c3ff02a25bb)

**Comment by bitonio** [comment] 2024-03-05 16:11
Hi there, closing as this is a duplicate of https://github.com/akamai/uls/issues/51

**Closed as completed by bitonio** 2024-03-05 16:11 UTC
Labels: duplicate
